apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  labels:
    app: amq-streams-demo
spec:
  kafka:
    version: 2.2.1
    replicas: 3
    listeners:
      tls:
        authentication: 
          type: tls
      plain: {}
    authorization:
      type: simple    
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.2"
      # new log segment every day
      log.roll.hours: 24
      # keep log segments 4 days
      log.retention.hours: 94
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
